# Use official Node.js image
FROM node

# Set working directory /ostadui
WORKDIR /ostadui

# Copy package*.json from OstadUI/
COPY OstadUI/package.json ./

# Install dependencies (npm install)
RUN npm install

# Copy frontend source code
COPY OstadUI/ .

# Expose port 5173
EXPOSE 5173

# Command to run frontend dev server: npm run dev
CMD ["npm", "run", "dev"]